Depend on .config.status.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,13 +39,13 @@ while true ; do
       chatBotName=$2
       shift 2;;
     --) shift; break;;
-    *) echo "Error!"; exit;;
+    *) echo "Error!"; exit 1;;
   esac
 done
 
 if [ -z "$domain" ]; then
   $0 --help
-  exit
+  exit 1
 fi
 
 if [ -z "$boshURL" ]; then
